### PR TITLE
Test either inputs have a length 0 or not

### PR DESCRIPTION
**Pull request by Jean-Romain**
Test if the inputs are equal to  `numeric(0)`

### CODE REVIEW

**Comment by Jean-Romain** [comment]
Ok I did some mess miss-merged you're repo and mine. But it's ok now.

**Comment by davidcsterratt** [comment]
Thanks very much for this. Unfortunately I've discovered that this still breaks my retistruct package. The behaviour of the "orig" algorithm for this input is actually:
```
tsearch(x, y, tri,  ps[,1], ps[,2], method="orig", bary=TRUE)
$idx
integer(0)

$p
     [,1] [,2] [,3]
```
Returning an error (as I suggested) therefore breaks the reverse dependency of my retistruct package. I'm sorry not to have realised this sooner!

There are two ways round this:

1. Modify the check in tsearch() to return the output above, i.e. make the code pass a test like this:
```
expect_equal(tsearch(x, y, tri, ps[,1], ps[,2]), list(idx=integer(0), p=matrix(0, 0, 3)))
```

2. My retistruct package actually calls `tsearchn()`, which then calls `tsearch()` in the case of 2D input. We could modify `tsearchn()`

I think I prefer option 1, as there may be people relying on this behaviour for their code to work. But I am open to persuasion.

Once again, sorry for  the bother!

**Comment by Jean-Romain** [comment]
I will preserve former behavior. This is the only good way

**Comment by Jean-Romain** [comment]
I did it at the R level. Error handling and weird case management should be tested at the R level (according to myself :smile: )

**Comment by davidcsterratt** [comment]
That's great - checking errors at the R level is fine. 

I'm hoping to submit the package to CRAN soon - today perhaps. Apart from a spellcheck, I don't think there's much to do. If you think of anything, please let me know soon.

**Pull request merged**
