### PR TITLE
 Testing whether a quantity is zero

### PR DESCRIPTION
**Pull request by Jean-Romain**
This new code should be almost the exact same computation method than the previous release. The only interesting commit is 7f0bd49

The `deldir` package has a parameter `eps` to test  whether a quantity is zero or not. It is set at `1.0e-9` by default. In octave this is hard coded and fixed to `1.0e-12`. I did the same. This explains the test results lines 83-102 in `test-tsearch.R` .

This is your choice to add or not a parameter `eps`. So far it should work like the previous release.

Btw, please ensure you have the lastest `Rcpp` version. The names of the automatic exports changed with the latest release.

### CODE REVIEW

**Comment by Jean-Romain** [comment]
Great!

In the documentation it is still written that the function is based on octave code. Don't forget to update.

**Comment by davidcsterratt** [comment]
Thanks. I will update the docs. I've started doing reverse dependency checking and manage to create a crash with some (admittedly weird input):
```
 x <- c(-1, -1, 1)
  y <- c(-1, 1, -1)
  p <- cbind(x, y)
  tri <- matrix(c(1, 2, 3), 1, 3)
  ## A subtle one! This gives numeric(0) as the final arguments...
  ps <- matrix(0, 0, 2)
  tsearch(x, y, tri, ps[,1], ps[,2])
```
While I was debugging this issue I put in some tests for faulty input, which I've just committed, along with the above test, commented out. Would you like to make a check to fix the problem and then uncomment the test?

**Comment by Jean-Romain** [comment]
`ps[,1]` and `ps[,2]` are `numeric(0)`. This is not expected to work and its creates a segfault. This should be tested at the R level in `tsearch.R`. I can add a test also in `Rtsearch.cpp` but if we make data integrity tests at the C++ level we have fewer flexibility compared to the R level.

**Comment by davidcsterratt** [comment]
Yes, I don't mind whether it's checked for in the R code or the C++ code. The C++ is not designed to be called directly, so let's go for the R code.

**Pull request merged**
