### PR TITLE
Cross link functions in docs

### PR DESCRIPTION
**Pull request by Bisaloo**
Hi,

While reading `geometry` docs, I tried to visit the documentation of a function listed in "See Also" and noticed that some of them did not contain a link. This PR aims at fixing this. 

I also changed a couple of minor syntax issues (`@@` in email address, `\item ` for enumerations and removed `paste()` in `message()`).

I notice that my text editor also removed the trailing whitespaces. [Here](https://github.com/davidcsterratt/geometry/pull/32/files?w=1) is a link to the diff without taking these changes into account. Let me know if you prefer I reverted these changes.

### CODE REVIEW

**Comment by Bisaloo** [comment]
I just pushed a 2nd commit to remove `paste()`s from `stop()`s and `warning()`s in the actual code. Please let me know if you'd prefer a different PR for that.

**Comment by davidcsterratt** [comment]
Thanks for the PR. It would be great if you could produce one that doesn't have all the whitespace changes. These might be desirable, but I need to check what my text editor's settings are, and it would be good to have them in a separate commit.

**Comment by Bisaloo** [comment]
@davidcsterratt, thanks for the quick feedback! It's done.

**Comment by davidcsterratt** [comment]
Thanks - now merged

**Pull request merged**
